// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX276kv0HATJbWrgCRAdx6UWMk0X0FY_o',
    appId: '1:883830384415:web:1c1cc3468d23faf8be722a',
    messagingSenderId: '883830384415',
    projectId: 'instaclone-e8567',
    authDomain: 'instaclone-e8567.firebaseapp.com',
    storageBucket: 'instaclone-e8567.appspot.com',
    measurementId: 'G-PHMQ8H8XEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCQ0uIrgy9NERFjy22IO3hFpZgPe_Hpc',
    appId: '1:883830384415:android:e6adc80bc49197d9be722a',
    messagingSenderId: '883830384415',
    projectId: 'instaclone-e8567',
    storageBucket: 'instaclone-e8567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQtAwwsJvAkygsVDHrn8tHiFWST8KI3BE',
    appId: '1:883830384415:ios:fbecb005c67df633be722a',
    messagingSenderId: '883830384415',
    projectId: 'instaclone-e8567',
    storageBucket: 'instaclone-e8567.appspot.com',
    iosClientId: '883830384415-scmes9cd1qmjhvb9v2h156m3o9d3ns5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
